### ISSUE TITLE
Not working in Docker

### ISSUE THREAD

**Issue by iBobik** [olipo186/Git-Auto-Deploy#93]
I tried to start it by Docker, but it exited on error code 0 without any messages or error codes.

```
> docker-compose up
Starting kmtravel_deployer_1
Attaching to kmtravel_deployer_1
kmtravel_deployer_1 exited with code 0
```
docker-compose.yml seem like:
```
deployer:
  image: qnch/github-gitlab-auto-deploy
  environment:
    GAD_REPO_URL: git@gitlab.com:my/repo.git
    GAD_REPO_DEPLOY: pwd
```
I know it propably will need SSH keys and maybe some other settings, but it should tell what it needs or print some error messages.
